### ISSUE TITLE
do more automagic in TAApp.TAObject

### ISSUE THREAD

**Issue by mador** [Schorny/timedAniJS#7]
maybe you can do more automagic in TAObject.
here is a quick example:

``` javascript
    new TAApp.TAObject(
        'headline',
        $headline,
        {
            inAni: fadeInHeadline,
            outAni: fadeOutHeadline
        },
        headlineSettings
    );
```

as you can see, i use "headline" a lot.
so - if i name the TAObject "headline" - you can look for a DOM-ele with the id "headline", the (rename if you want) "fadeInHeadline" and "fadeOutHeadline" TAVelocityAnimation's and "headlineSettings".

optional you can use your own declared selector, in/outAni and settings.

the magical code would look somthing like that:

``` javascript
    new TAApp.TAObject({name: 'headline'});
```

or with a custom outAni:

``` javascript
    new TAApp.TAObject({
        name: 'headline',
        ani: {
            out: myCustomNamedOutAni
        }
   });
```

(i think you have to use one options object [cause there is no parameterlist])

**Comment by Schorny** [comment]
In v2 there is now a Object.clone() function that clones an object and lets you overwrite some settings like:

``` javascript
    var o = TA.createObjectFromId(
        'headline',
        {
            in: fadeInHeadline,
            out: fadeOutHeadline
        },
        headlineSettings
    );

    o.clone({name: 'headline2'});
```
